m=[9,1,3,2,6]
print(len(m))
print(max(m))
print(min(m))
m.append(7)
print(m)
m.insert(2,8)
print(m)
m.pop()
print(m)
m.remove(3)
print(m)
a=9
b=1

print(a,b)
a,b=b,a
print(a,b)
k=[8,1,4,9,3]
k.reverse()
print(k)
k.sort()
print(k)
print(k[::-1])
tp=(1,2,3)
print(tp)
print(tp[1])
s="mubashir",1,2,3
print(s)
print(s[0:2])
sm="mubashirisagood1boy"
print("ss",sm[::-1])
print(sm.find("boy"))
print(len(sm))
print(sm.capitalize())
print(sm.lower())
print(sm.upper())
print(sm.replace("boy","girl"))
print(sm.count("s"))
print(sm.isalpha())
print(sm.isnumeric())
