mstr="mubashir is a good boy"
print(mstr[8:12])
# print(len(mstr))
# print(mstr[0])
# print(mstr[0:5])
# print(mstr[0:5:2])
# print(mstr[::])
# print(mstr[::3])
# print(mstr[-4:-1])
# print(mstr[-4:21])
# print(mstr.count("b"))
# print(mstr.isalnum() )
# print(mstr.isalpha())
# print(mstr.endswith("is"))
# print(mstr.find("ba"))
# print(mstr.upper())
# print(mstr.lower())
# print(mstr.capitalize())
# print(mstr.replace("a","and"))
# print(mstr.reverse())